#
# VillagerName 0.3
# by frdmn (http://frd.mn)
#

log: true
farmer:
- 'Adelaide'
- 'Aelfwald'
- 'Aelfweard'
- 'Aethelbald'
- 'Aethelberth'
- 'Aethelbert'
- 'Aethelnoth'
- 'Aethelred'
- 'Aethelweard'
- 'Aethelwold'
- 'Aethelwulf'
- 'Aleida'
- 'Alexia'
- 'Alfred'
- 'Alice'
- 'Alix'
- 'Althalos'
- 'Alweo'
- 'Angmar'
- 'Arabella'
- 'Ariana'
- 'Arthur'
- 'Asher'
- 'Atheena'
- 'Athelstan'
- 'Barda'
- 'Beatrix'
- 'Benedict'
- 'Beorhtwulf'
- 'Beornred'
- 'Beornwulf'
- 'Berhtwald'
- 'Borin'
- 'Brom'
librarian:
- 'Brorda'
- 'Brunhild'
- 'Bryce'
- 'Burghred'
- 'Cadfil'
- 'Carac'
- 'Cassius'
- 'Catrain'
- 'Ceawlin'
- 'Cedric'
- 'Cenred'
- 'Cenwealh'
- 'Cenwulf'
- 'Ceolwulf'
- 'Cerdic'
- 'Clotilde'
- 'Creoda'
- 'Cristiana'
- 'Cutha'
- 'Cuthwine'
- 'Cynric'
- 'Dain'
- 'Destrian'
- 'Dimia'
- 'Donald'
- 'Doran'
- 'Eadbald'
- 'Eadberht'
- 'Eadred'
- 'Eadric'
- 'Eadwig'
- 'Eanulf'
- 'Eawa'
- 'Ecgfrith'
priest:
- 'Edmund'
- 'Egbert'
- 'Eginhard'
- 'Eglantine'
- 'Egric'
- 'Eleanor'
- 'Elizabeth'
- 'Emeline'
- 'Eni'
- 'Enndolynn'
- 'Eomaer'
- 'Eorpwald'
- 'Favian'
- 'Fendrel'
- 'Forthwind'
- 'Frederick'
- 'Frithogar'
- 'Gavin'
- 'Geoffrey'
- 'Godiva'
- 'Gregory'
- 'Guinevere'
- 'Gussalen'
- 'Gwendolynn'
- 'Hadrian'
- 'Hathored'
- 'Hawise'
- 'Helena'
- 'Heloise'
- 'Henry'
- 'Hildegard'
- 'Hubert'
- 'Hygeberht'
- 'Icil'
blacksmith:
- 'Ine'
- 'Ingild'
- 'Isabel'
- 'Isolde'
- 'Jaenberht'
- 'Janet'
- 'Janshai'
- 'Jarin'
- 'Jasmine'
- 'Josef'
- 'Josselyn'
- 'Juliana'
- 'Katelyn'
- 'Katrina'
- 'Kaylein'
- 'Krea'
- 'Leo'
- 'Leofrick'
- 'Letholdus'
- 'Lief'
- 'Loreena'
- 'Luanda'
- 'Maerwynn'
- 'Margaret'
- 'Maria'
- 'Matilda'
- 'Matilde'
- 'Merek'
- 'Mirabelle'
- 'Muriel'
- 'Odda'
- 'Offa'
- 'Osmod'
- 'Penda'
butcher:
- 'Peter'
- 'Peyton'
- 'Phrowenia'
- 'Pybba'
- 'Quinn'
- 'Raegenhere'
- 'Rainydayas'
- 'Ranulph'
- 'Reginald'
- 'Robin'
- 'Ronald'
- 'Rose'
- 'Rowan'
- 'Rowena'
- 'Rulf'
- 'Sadon'
- 'Seraphina'
- 'Sigebert'
- 'Terrowin'
- 'Terryn'
- 'Thingfrith'
- 'Thomas'
- 'Tybalt'
- 'Tyttla'
- 'Ulric'
- 'Victoria'
- 'Vladimere'
- 'Walter'
- 'Wehha'
- 'Winifred'
- 'Wuffa'
other:
- 'Wulfhere'
- 'Xalvador'
- 'Zane'